import { Client, EmbedBuilder } from "discord.js";

export default function buildEmbed(
  title: string,
  desc: string,
  color: "Red" | "Green" | "Random",
  client: Client
): EmbedBuilder {
  const embed = new EmbedBuilder()
    .setColor(color)
    .setTitle(title)
    .setDescription(desc)
    .setFooter({
      text: "Generated by Dis-Cogs ⚙️",
      iconURL: client.user?.displayAvatarURL(),
    })
    .setTimestamp();

  return embed;
}
